# Generated by Django 4.2.2 on 2023-06-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('email_text', models.TextField(blank=True, null=True, verbose_name='Email Text (HTML Field)')),
                ('source', models.CharField(choices=[('SM', 'Social Media'), ('IF', 'Instagram Followers'), ('IFG', 'Instagram Following'), ('LC', 'LinkedIn Company'), ('WB', 'Website')], max_length=10, verbose_name='Source')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
    ]
