# Generated by Django 4.2.2 on 2023-06-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='value',
            field=models.CharField(choices=[('SM', 'Social Media'), ('IF', 'Instagram Followers'), ('IFG', 'Instagram Following'), ('LC', 'LinkedIn Company'), ('WB', 'Website')], max_length=10, verbose_name='Values'),
        ),
    ]
