# Generated by Django 4.2.2 on 2023-06-17 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_leads_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Source (Social Media)')),
                ('follower', models.IntegerField(blank=True, null=True, verbose_name='Follower')),
                ('following', models.IntegerField(blank=True, null=True, verbose_name='Following')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Profile Record',
                'verbose_name_plural': 'Profile Records',
            },
        ),
    ]
