# Generated by Django 4.2.2 on 2023-06-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_profilerecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='source',
            field=models.CharField(choices=[('IF', 'Instagram Followers'), ('IFG', 'Instagram Following'), ('LC', 'LinkedIn Company'), ('WB', 'Website')], max_length=10, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Values'),
        ),
    ]
