# Generated by Django 4.2.2 on 2023-06-18 01:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_leads_source_alter_leads_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='email_text',
        ),
        migrations.AddField(
            model_name='leads',
            name='email_body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='email_subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Subject'),
        ),
        migrations.AddField(
            model_name='leads',
            name='send_mail',
            field=models.BooleanField(default=False, verbose_name='Send Emails?'),
        ),
    ]
