# Generated by Django 4.2.2 on 2023-06-27 14:27

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_leads_source_alter_profilerecords_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsEmail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Subject')),
                ('email_body', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.RemoveField(
            model_name='leads',
            name='email_body',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='email_subject',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='send_mail',
        ),
        migrations.AlterField(
            model_name='leads',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('status', models.CharField(choices=[('r', 'Running'), ('c', 'Completed'), ('s', 'Stopped')], max_length=100)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Task Status',
                'verbose_name_plural': 'Task Status',
            },
        ),
    ]
