# Generated by Django 4.2.2 on 2023-06-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_leadsemail_remove_leads_email_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('r', 'Running'), ('c', 'Completed'), ('s', 'Stopped')], default='r', max_length=100),
        ),
    ]
