# Generated by Django 4.2.2 on 2023-06-29 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsemail',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leads', verbose_name='Lead'),
        ),
    ]
