# Generated by Django 4.2.2 on 2023-06-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_leadsemail_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='source',
            field=models.CharField(choices=[('IFG', 'Instagram Following'), ('WB', 'Website')], max_length=10, verbose_name='Source'),
        ),
    ]
