# Generated by Django 4.2.2 on 2023-06-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipedrive_api', models.CharField(default='default_pipedrive_api', max_length=100, verbose_name='Pipedrive Api')),
                ('instagram_email', models.EmailField(default='default_instagram_email', max_length=100, verbose_name='Instagram Email/Username')),
                ('instagram_password', models.CharField(default='default_instagram_password', max_length=100, verbose_name='Instagram Password')),
                ('linkedin_email', models.EmailField(default='default_linkedin_email', max_length=100, verbose_name='Linkedin Email/Username')),
                ('linkedin_password', models.CharField(default='default_linkedin_password', max_length=100, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'Social Media Credentials',
                'verbose_name_plural': 'Social MEdia Credentials',
            },
        ),
    ]
