# Generated by Django 4.2.2 on 2023-06-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediacredentials',
            options={'verbose_name': 'Social Media Credentials', 'verbose_name_plural': 'Social Media Credentials'},
        ),
    ]
