# Generated by Django 4.2.2 on 2023-06-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialCredentials',
        ),
    ]
